const SUPABASE_URL="https://qvxoxrzvxyyribqjnpkb.supabase.co";
const SUPABASE_KEY="sb_publishable_1zOA0YpTtJkNYsmm4zXxsA_wSJpdHKe";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);const track=(event_name,target_key=null)=>sb.from("analytics_events").insert({service_key:"vocalinkfind",event_name,page_path:location.pathname||"/",target_key,metadata:{}}).then(()=>{}).catch(()=>{});track("page_view");
const map=L.map("map",{zoomControl:false}).setView([35.681236,139.767125],5);
L.control.zoom({position:"bottomright"}).addTo(map);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);
let session=null,watchId=null,myCircle=null,channel=null,markers=new Map(),locationShareTracked=false;
function msg(t){$("message").textContent=t}
function setLocationStatus(t){$("locationStatus").textContent=t}
async function refreshPermissionStatus(){
  if(!navigator.geolocation){setLocationStatus("位置情報非対応");return "unsupported"}
  if(!navigator.permissions?.query)return "unknown";
  try{
    const permission=await navigator.permissions.query({name:"geolocation"});
    const apply=()=>{if(watchId===null)setLocationStatus(permission.state==="granted"?"許可済み・停止中":permission.state==="denied"?"権限拒否":"許可待ち")};
    apply();permission.onchange=apply;return permission.state;
  }catch{return "unknown"}
}
function markerFor(userId,loc,label){const p=[loc.latitude,loc.longitude];let m=markers.get(userId);if(!m){m=L.marker(p).addTo(map);markers.set(userId,m)}else m.setLatLng(p);m.bindPopup((label||"共有メンバー")+"<br><small>更新: "+new Date(loc.updated_at||Date.now()).toLocaleTimeString("ja-JP")+"</small>");return m}
async function refreshLocations(){if(!session)return;const {data,error}=await sb.from("user_locations").select("user_id,latitude,longitude,accuracy,updated_at");if(error){msg("位置情報の取得に失敗: "+error.message);return}for(const loc of data)markerFor(loc.user_id,loc,loc.user_id===session.user.id?"自分":"共有メンバー");if(data.length){const latest=data.slice().sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at))[0];$("lastUpdated").textContent="最終更新 "+new Date(latest.updated_at).toLocaleString("ja-JP")}}
async function publishPosition(pos){const c=pos.coords;const {error}=await sb.from("user_locations").upsert({user_id:session.user.id,latitude:c.latitude,longitude:c.longitude,accuracy:c.accuracy||null,updated_at:new Date().toISOString()});if(error)msg("位置情報の保存に失敗: "+error.message)}
function locationSuccess(pos){if(!locationShareTracked){locationShareTracked=true;track("location_share_start")}const c=pos.coords;const loc={latitude:c.latitude,longitude:c.longitude,accuracy:c.accuracy,updated_at:new Date().toISOString()};markerFor(session.user.id,loc,"自分").openPopup();if(myCircle)map.removeLayer(myCircle);myCircle=L.circle([c.latitude,c.longitude],{radius:c.accuracy||30,color:"#4f6b5a",fillColor:"#4f6b5a",fillOpacity:.1,weight:1}).addTo(map);map.setView([c.latitude,c.longitude],16);setLocationStatus("共有中");$("lastUpdated").textContent="自分の位置を更新 "+new Date().toLocaleTimeString("ja-JP");publishPosition(pos)}
function locationError(e){if(e.code===1&&watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null}setLocationStatus(e.code===1?"権限拒否":"取得できません");msg(({1:"位置情報の利用が許可されていません",2:"位置情報を取得できませんでした",3:"位置情報の取得がタイムアウトしました"})[e.code]||"位置情報の取得に失敗しました")}
async function startLocation(){if(!navigator.geolocation){msg("このブラウザは位置情報に対応していません");setLocationStatus("位置情報非対応");return}if(watchId!==null){msg("位置情報はすでに共有中です");return}const permission=await refreshPermissionStatus();if(permission==="denied"){setLocationStatus("権限拒否");msg("ブラウザで位置情報が拒否されています。サイト設定から位置情報を許可してから再度お試しください。");return}setLocationStatus("許可確認中…");locationShareTracked=false;watchId=navigator.geolocation.watchPosition(locationSuccess,locationError,{enableHighAccuracy:true,timeout:15000,maximumAge:5000})}
function stopLocation(){if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null;if(locationShareTracked){track("location_share_stop");locationShareTracked=false}}setLocationStatus("停止中")}
function shareStatus(s){if(!s.active)return"停止中";if(s.expires_at&&new Date(s.expires_at)<=new Date())return"期限切れ";return"有効"}
function esc(t){return String(t??"").replace(/[&<>"\']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","\'":"&#039;"}[c]))}
async function loadOwnedShares(){if(!session)return;const box=$("ownedShares");box.innerHTML='<p class="muted">共有を読み込み中...</p>';const {data:shares,error}=await sb.from("location_shares").select("id,share_code,title,active,expires_at,created_at").eq("owner_id",session.user.id).order("created_at",{ascending:false});if(error){box.innerHTML='<p class="form-message">共有一覧を取得できませんでした。</p>';return}if(!shares.length){box.innerHTML='<p class="muted">作成した共有はありません。</p>';return}const ids=shares.map(s=>s.id);const {data:members}=await sb.from("location_share_members").select("share_id").in("share_id",ids);const counts={};for(const m of members||[])counts[m.share_id]=(counts[m.share_id]||0)+1;box.innerHTML=shares.map(s=>`<article style="border:1px solid #ddd6ca;border-radius:12px;padding:12px"><strong>${esc(s.title)}</strong><div class="muted" style="margin:5px 0">${esc(s.share_code)} / ${shareStatus(s)} / 参加 ${counts[s.id]||0}人</div><div style="display:flex;gap:6px;flex-wrap:wrap"><button class="secondary-button small" data-share-toggle="${s.id}" data-active="${s.active}">${s.active?"停止":"再開"}</button><button class="secondary-button small" data-share-delete="${s.id}">削除</button></div></article>`).join("")}
async function toggleShare(id,active){const {error}=await sb.from("location_shares").update({active:!active,updated_at:new Date().toISOString()}).eq("id",id).eq("owner_id",session.user.id);if(error){msg("共有状態を変更できませんでした: "+error.message);return}msg(active?"共有を停止しました。":"共有を再開しました。");await loadOwnedShares();await refreshLocations()}
async function deleteShare(id){if(!confirm("この共有を削除しますか？"))return;const {error}=await sb.from("location_shares").delete().eq("id",id).eq("owner_id",session.user.id);if(error){msg("共有を削除できませんでした: "+error.message);return}msg("共有を削除しました。");await loadOwnedShares();await refreshLocations()}
function createShare(){const title=$("shareTitle").value.trim()||"位置情報共有";const hours=$("shareExpiry").value;const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let code="VF-";for(let i=0;i<6;i++)code+=chars[Math.floor(Math.random()*chars.length)];const expires=hours?new Date(Date.now()+Number(hours)*3600000).toISOString():null;sb.from("location_shares").insert({owner_id:session.user.id,share_code:code,title,expires_at:expires}).select().single().then(({data,error})=>{if(error){msg("共有作成に失敗: "+error.message);return}$("shareCode").textContent=data.share_code;track("share_create");msg("共有コードを作成しました。相手にこのコードを伝えてください。");loadOwnedShares()})}
async function joinShare(){const code=$("joinCode").value.trim();if(!code){msg("共有コードを入力してください");return}const {error}=await sb.rpc("join_location_share",{p_share_code:code});if(error){msg("参加できません: "+error.message);return}track("share_join");msg("共有に参加しました。");await refreshLocations()}
function subscribeRealtime(){if(channel)sb.removeChannel(channel);channel=sb.channel("vocalinkfind-locations").on("postgres_changes",{event:"*",schema:"public",table:"user_locations"},payload=>{if(payload.new?.user_id)markerFor(payload.new.user_id,payload.new,payload.new.user_id===session.user.id?"自分":"共有メンバー");$("lastUpdated").textContent="リアルタイム更新 "+new Date().toLocaleTimeString("ja-JP")}).subscribe()}
async function init(){const {data:{session:s}}=await sb.auth.getSession();session=s;if(session)track("login_success");if(!session){location.href="login.html";return}$("authStatus").textContent=session.user.email||"ログイン中";await refreshPermissionStatus();await refreshLocations();await loadOwnedShares();subscribeRealtime()}
window.addEventListener("pagehide",()=>{stopLocation();if(channel){sb.removeChannel(channel);channel=null}});
$("ownedShares").addEventListener("click",e=>{const t=e.target.closest("[data-share-toggle]");if(t)toggleShare(t.dataset.shareToggle,t.dataset.active==="true");const d=e.target.closest("[data-share-delete]");if(d)deleteShare(d.dataset.shareDelete)});$("refreshShares").addEventListener("click",loadOwnedShares);$("startLocation").addEventListener("click",startLocation);$("stopLocation").addEventListener("click",stopLocation);$("createShare").addEventListener("click",createShare);$("joinShare").addEventListener("click",joinShare);$("logoutButton").addEventListener("click",async()=>{stopLocation();await sb.auth.signOut();location.href="login.html"});init();